from .exceptions import (
    APIError, 
    BadRequest, 
    Unauthorized,
    Forbidden,
    NotFound,
    MethodNotAllowed,
    NotAcceptable,
    Conflict,
    Gone,
    LengthRequired,
    PreconditionFailed,
    RequestEntityTooLarge,
    UnsupportedMediaType,
    RequestedRangeNotSatisfiable,
    UnprocessableEntity,
    TooManyRequests,
    InternalServerError,
    NotImplemented,
    ServiceUnavailable,
    InsufficientStorage,
    BandwidthLimitExceeded
)

API_exception_mapping : 'dict[int, type[APIError]]' = {
    #status code: exception class
    400: BadRequest,
    401: Unauthorized,
    403: Forbidden,
    404: NotFound,
    405: MethodNotAllowed,
    406: NotAcceptable,
    409: Conflict,
    410: Gone,
    411: LengthRequired,
    412: PreconditionFailed,
    413: RequestEntityTooLarge,
    415: UnsupportedMediaType,
    416: RequestedRangeNotSatisfiable,
    422: UnprocessableEntity,
    429: TooManyRequests,
    500: InternalServerError,
    501: NotImplemented,
    503: ServiceUnavailable,
    507: InsufficientStorage,
    509: BandwidthLimitExceeded
}

API_exception_description : 'dict[str, str]' = {
    "accessDenied": "The caller doesn't have permission to perform the action.",
    "activityLimitReached": "The app or user has been throttled.",
    "generalException": "An unspecified error has occurred.",
    "invalidRange": "The specified byte range is invalid or unavailable.",
    "invalidRequest": "The request is malformed or incorrect.",
    "itemNotFound": "The resource could not be found.",
    "malwareDetected": "Malware was detected in the requested resource.",
    "nameAlreadyExists": "The specified item name already exists.",
    "notAllowed": "The action is not allowed by the system.",
    "notSupported": "The request is not supported by the system.",
    "resourceModified": "The resource being updated has changed since the caller last read it, usually an eTag mismatch.",
    "resyncRequired": "The delta token is no longer valid, and the app must reset the sync state.",
    "serviceNotAvailable": "The service is not available. Try the request again after a delay. There may be a Retry-After header.",
    "quotaLimitReached": "The user has reached their quota limit.",
    "unauthenticated": "The caller is not authenticated.",
    "accessRestricted": "Access restricted to the item's owner.",
    "cannotSnapshotTree": "Failed to get a consistent delta snapshot. Try again later.",
    "childItemCountExceeded": "Max limit on the number of child items was reached.",
    "entityTagDoesNotMatch": "ETag does not match the current item's value.",
    "fragmentLengthMismatch": "Declared total size for this fragment is different from that of the upload session.",
    "fragmentOutOfOrder": "Uploaded fragment is out of order.",
    "fragmentOverlap": "Uploaded fragment overlaps with existing data.",
    "invalidAcceptType": "Invalid accept type.",
    "invalidParameterFormat": "Invalid parameter format.",
    "invalidPath": "Name contains invalid characters.",
    "invalidQueryOption": "Invalid query option.",
    "invalidStartIndex": "Invalid start index.",
    "lockMismatch": "Lock token does not match existing lock.",
    "lockNotFoundOrAlreadyExpired": "There is currently no unexpired lock on the item.",
    "lockOwnerMismatch": "Lock Owner ID does not match provided ID.",
    "malformedEntityTag": "ETag header is malformed. ETags must be quoted strings.",
    "maxDocumentCountExceeded": "Max limit on number of Documents is reached.",
    "maxFileSizeExceeded": "Max file size exceeded.",
    "maxFolderCountExceeded": "Max limit on number of Folders is reached.",
    "maxFragmentLengthExceeded": "Max file size exceeded.",
    "maxItemCountExceeded": "Max limit on number of Items is reached.",
    "maxQueryLengthExceeded": "Max query length exceeded.",
    "maxStreamSizeExceeded": "Maximum stream size exceeded.",
    "parameterIsTooLong": "Parameter Exceeds Maximum Length.",
    "parameterIsTooSmall": "Parameter is smaller then minimum value.",
    "pathIsTooLong": "Path exceeds maximum length.",
    "pathTooDeep": "Folder hierarchy depth limit reached.",
    "propertyNotUpdateable": "Property not updateable.",
    "resyncApplyDifferences": "Resync required. Replace any local items with the server's version (including deletes) if you're sure that the service was up to date with your local changes when you last sync'd. Upload any local changes that the server doesn't know about.",
    "resyncRequired": "Resync is required.",
    "resyncUploadDifferences": "Resync required. Upload any local items that the service did not return, and upload any files that differ from the server's version (keeping both copies if you're not sure which one is more up-to-date).",
    "serviceNotAvailable": "The server is unable to process the current request.",
    "serviceReadOnly": "Resource is temporarily read-only.",
    "throttledRequest": "Too many requests.",
    "tooManyResultsRequested": "Too many results requested.",
    "tooManyTermsInQuery": "Too many terms in the query.",
    "totalAffectedItemCountExceeded": "Operation is not allowed because the number of affected items exceeds threshold.",
    "truncationNotAllowed": "Data truncation is not allowed.",
    "uploadSessionFailed": "Upload session failed.",
    "uploadSessionIncomplete": "Upload session incomplete.",
    "uploadSessionNotFound": "Upload session not found.",
    "virusSuspicious": "This document is suspicious and may have a virus.",
    "zeroOrFewerResultsRequested": "Zero or fewer results requested."
}